apiVersion: v1
kind: ConfigMap
metadata:
  name: harness-argocd-adapter
  namespace: argocd
data:
  ARGO_CD_URL: <ArgoCdServerURL>
  ALLOWED_ORIGINS: https://app.harness.io,https://localhost

---
apiVersion: v1
kind: Service
metadata:
  name: harness-argocd-adapter
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: harness-argocd-adapter
  loadBalancerSourceRanges:
    - <AllowedIP1>
    - <AllowedIP2>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-argocd-adapter
  namespace: argocd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: harness-argocd-adapter
  template:
    metadata:
      labels:
        app: harness-argocd-adapter
    spec:
      containers:
      - name: harness-argocd-adapter
        image: harness/argocd-ui-proxy:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: harness-argocd-adapter
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz?full=true
            port: 8080
