apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-example
spec:
  generators:
  - git:
      repoURL: https://github.com/wings-software/harness-docs.git
      revision: HEAD
      files:
      - path: "gitops-appset/app1/*/config.json"
  template:
    metadata:
      name: 'app1-{{cluster.name}}'
    spec:
      project: b062fb30
      source:
        repoURL: https://github.com/wings-software/harness-docs.git
        targetRevision: '{{releaseTag}}'
        path: "gitops/guestbook"
        helm:
          parameters:
            - name: version
              value: '{{version}}'
      destination:
        server: '{{cluster.address}}'
        namespace: br-agent
      syncPolicy:
        automated: {}
